### ISSUE TITLE
assert.expect params overriden when completeExistingMessages enabled

### ISSUE THREAD

**Issue by sdebarros** [wyeworks/ember-qunit-nice-errors#38]
As reported by @les2 in https://github.com/les2/ember-qunit-nice-errors-issue-18 and demonstrated in https://github.com/les2/ember-qunit-nice-errors-issue-18, when the *completeExistingMessages* option is set to true, `assert.expect(10)` gets replaced by `assert.expect('assert.expect(10)')` causing the test to fail.

**Comment by fedekau** [comment]
@les2 this has been fixed, you should be able to use this with v1.1.1!

**Comment by les2** [comment]
@fedekau thank you! just updated on work project and everything works!
