### ISSUE TITLE
Add option to add human readable messages to assertions

### ISSUE THREAD

**Issue by fedekau** [wyeworks/ember-qunit-nice-errors#45]
Right now messages are ok for developers, but probable not so good for normal people (Developers are not normal by default, and you know that!), for example  `assert.equal('Hello', 'Good bye')` could be replaced by `Comparing if 'Hello' is equal to 'Good bye'`.

This would play nicely with this amazing addon [telling-stories](https://github.com/mvdwg/telling-stories)

**Comment by san650** [comment]
Is there a way to convert something like `assert.ok(page.button.isVisible)` to `Button is visible`?.

The idea would be to take `page.button.isVisible` as a string, removing some black listed words (prefixes) and then using something like Rails [`humanize`](http://apidock.com//rails/ActiveSupport/Inflector/humanize) on the string.

**Comment by san650** [comment]
Doesn't sound relevant anymore (telling-stories addon is not going to happen any time soon).
